### ISSUE TITLE
Atom Link Not present in Meta Tags + Incorrect href

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [cpury/cpury.github.io#1]
Hello @cpury,

Very nice blog, only two remarks:
* You should add the RSS / Atom feed in <link> to all your pages. Quite complicated to look for it in automatic discovery
* You should fix your Atom link: http://cpury.github.io/feed.xml: `<atom:link href="https://cpury.github.io//feed.xml" rel="self" type="application/rss+xml"/>` => This is an invalid address: cpury.github.io **//** feed.xml

Have a great day,

Jonathan

**Comment by cpury** [comment]
Thanks for taking the time to give me feedback, Jonathan! Glad you like the blog.

I fixed the link and added a RSS `<link>` to the head. I hope this helps.

**Comment by DEKHTIARJonathan** [comment]
No problem @cpury, I confirm that it is corectly working ;)
